/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KasirIndexRouteImport } from './routes/kasir.index'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as KasirScanRouteImport } from './routes/kasir.scan'
import { Route as KasirProfileRouteImport } from './routes/kasir.profile'
import { Route as KasirPaymentRouteImport } from './routes/kasir.payment'
import { Route as KasirPackagesRouteImport } from './routes/kasir.packages'
import { Route as KasirNotifyRouteImport } from './routes/kasir.notify'
import { Route as KasirNewOrderRouteImport } from './routes/kasir.new-order'
import { Route as KasirHandoverRouteImport } from './routes/kasir.handover'
import { Route as KasirCouriersRouteImport } from './routes/kasir.couriers'
import { Route as KasirComplaintsRouteImport } from './routes/kasir.complaints'
import { Route as KasirChatsRouteImport } from './routes/kasir.chats'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminCouriersRouteImport } from './routes/admin.couriers'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'

const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KasirIndexRoute = KasirIndexRouteImport.update({
  id: '/kasir/',
  path: '/kasir/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/customer/',
  path: '/customer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const KasirScanRoute = KasirScanRouteImport.update({
  id: '/kasir/scan',
  path: '/kasir/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const KasirProfileRoute = KasirProfileRouteImport.update({
  id: '/kasir/profile',
  path: '/kasir/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const KasirPaymentRoute = KasirPaymentRouteImport.update({
  id: '/kasir/payment',
  path: '/kasir/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const KasirPackagesRoute = KasirPackagesRouteImport.update({
  id: '/kasir/packages',
  path: '/kasir/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const KasirNotifyRoute = KasirNotifyRouteImport.update({
  id: '/kasir/notify',
  path: '/kasir/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const KasirNewOrderRoute = KasirNewOrderRouteImport.update({
  id: '/kasir/new-order',
  path: '/kasir/new-order',
  getParentRoute: () => rootRouteImport,
} as any)
const KasirHandoverRoute = KasirHandoverRouteImport.update({
  id: '/kasir/handover',
  path: '/kasir/handover',
  getParentRoute: () => rootRouteImport,
} as any)
const KasirCouriersRoute = KasirCouriersRouteImport.update({
  id: '/kasir/couriers',
  path: '/kasir/couriers',
  getParentRoute: () => rootRouteImport,
} as any)
const KasirComplaintsRoute = KasirComplaintsRouteImport.update({
  id: '/kasir/complaints',
  path: '/kasir/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const KasirChatsRoute = KasirChatsRouteImport.update({
  id: '/kasir/chats',
  path: '/kasir/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/admin/packages',
  path: '/admin/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCouriersRoute = AdminCouriersRouteImport.update({
  id: '/admin/couriers',
  path: '/admin/couriers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/couriers': typeof AdminCouriersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/kasir/chats': typeof KasirChatsRoute
  '/kasir/complaints': typeof KasirComplaintsRoute
  '/kasir/couriers': typeof KasirCouriersRoute
  '/kasir/handover': typeof KasirHandoverRoute
  '/kasir/new-order': typeof KasirNewOrderRoute
  '/kasir/notify': typeof KasirNotifyRoute
  '/kasir/packages': typeof KasirPackagesRoute
  '/kasir/payment': typeof KasirPaymentRoute
  '/kasir/profile': typeof KasirProfileRoute
  '/kasir/scan': typeof KasirScanRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/kasir/': typeof KasirIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/couriers': typeof AdminCouriersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/kasir/chats': typeof KasirChatsRoute
  '/kasir/complaints': typeof KasirComplaintsRoute
  '/kasir/couriers': typeof KasirCouriersRoute
  '/kasir/handover': typeof KasirHandoverRoute
  '/kasir/new-order': typeof KasirNewOrderRoute
  '/kasir/notify': typeof KasirNotifyRoute
  '/kasir/packages': typeof KasirPackagesRoute
  '/kasir/payment': typeof KasirPaymentRoute
  '/kasir/profile': typeof KasirProfileRoute
  '/kasir/scan': typeof KasirScanRoute
  '/admin': typeof AdminIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/kasir': typeof KasirIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/couriers': typeof AdminCouriersRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/kasir/chats': typeof KasirChatsRoute
  '/kasir/complaints': typeof KasirComplaintsRoute
  '/kasir/couriers': typeof KasirCouriersRoute
  '/kasir/handover': typeof KasirHandoverRoute
  '/kasir/new-order': typeof KasirNewOrderRoute
  '/kasir/notify': typeof KasirNotifyRoute
  '/kasir/packages': typeof KasirPackagesRoute
  '/kasir/payment': typeof KasirPaymentRoute
  '/kasir/profile': typeof KasirProfileRoute
  '/kasir/scan': typeof KasirScanRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/kasir/': typeof KasirIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/admin/audit'
    | '/admin/couriers'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/packages'
    | '/admin/profile'
    | '/admin/reports'
    | '/kasir/chats'
    | '/kasir/complaints'
    | '/kasir/couriers'
    | '/kasir/handover'
    | '/kasir/new-order'
    | '/kasir/notify'
    | '/kasir/packages'
    | '/kasir/payment'
    | '/kasir/profile'
    | '/kasir/scan'
    | '/admin/'
    | '/customer/'
    | '/kasir/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/admin/audit'
    | '/admin/couriers'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/packages'
    | '/admin/profile'
    | '/admin/reports'
    | '/kasir/chats'
    | '/kasir/complaints'
    | '/kasir/couriers'
    | '/kasir/handover'
    | '/kasir/new-order'
    | '/kasir/notify'
    | '/kasir/packages'
    | '/kasir/payment'
    | '/kasir/profile'
    | '/kasir/scan'
    | '/admin'
    | '/customer'
    | '/kasir'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/admin/audit'
    | '/admin/couriers'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/packages'
    | '/admin/profile'
    | '/admin/reports'
    | '/kasir/chats'
    | '/kasir/complaints'
    | '/kasir/couriers'
    | '/kasir/handover'
    | '/kasir/new-order'
    | '/kasir/notify'
    | '/kasir/packages'
    | '/kasir/payment'
    | '/kasir/profile'
    | '/kasir/scan'
    | '/admin/'
    | '/customer/'
    | '/kasir/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCouriersRoute: typeof AdminCouriersRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportsRoute: typeof AdminReportsRoute
  KasirChatsRoute: typeof KasirChatsRoute
  KasirComplaintsRoute: typeof KasirComplaintsRoute
  KasirCouriersRoute: typeof KasirCouriersRoute
  KasirHandoverRoute: typeof KasirHandoverRoute
  KasirNewOrderRoute: typeof KasirNewOrderRoute
  KasirNotifyRoute: typeof KasirNotifyRoute
  KasirPackagesRoute: typeof KasirPackagesRoute
  KasirPaymentRoute: typeof KasirPaymentRoute
  KasirProfileRoute: typeof KasirProfileRoute
  KasirScanRoute: typeof KasirScanRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  KasirIndexRoute: typeof KasirIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasir/': {
      id: '/kasir/'
      path: '/kasir'
      fullPath: '/kasir/'
      preLoaderRoute: typeof KasirIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/customer'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasir/scan': {
      id: '/kasir/scan'
      path: '/kasir/scan'
      fullPath: '/kasir/scan'
      preLoaderRoute: typeof KasirScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasir/profile': {
      id: '/kasir/profile'
      path: '/kasir/profile'
      fullPath: '/kasir/profile'
      preLoaderRoute: typeof KasirProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasir/payment': {
      id: '/kasir/payment'
      path: '/kasir/payment'
      fullPath: '/kasir/payment'
      preLoaderRoute: typeof KasirPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasir/packages': {
      id: '/kasir/packages'
      path: '/kasir/packages'
      fullPath: '/kasir/packages'
      preLoaderRoute: typeof KasirPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasir/notify': {
      id: '/kasir/notify'
      path: '/kasir/notify'
      fullPath: '/kasir/notify'
      preLoaderRoute: typeof KasirNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasir/new-order': {
      id: '/kasir/new-order'
      path: '/kasir/new-order'
      fullPath: '/kasir/new-order'
      preLoaderRoute: typeof KasirNewOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasir/handover': {
      id: '/kasir/handover'
      path: '/kasir/handover'
      fullPath: '/kasir/handover'
      preLoaderRoute: typeof KasirHandoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasir/couriers': {
      id: '/kasir/couriers'
      path: '/kasir/couriers'
      fullPath: '/kasir/couriers'
      preLoaderRoute: typeof KasirCouriersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasir/complaints': {
      id: '/kasir/complaints'
      path: '/kasir/complaints'
      fullPath: '/kasir/complaints'
      preLoaderRoute: typeof KasirComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasir/chats': {
      id: '/kasir/chats'
      path: '/kasir/chats'
      fullPath: '/kasir/chats'
      preLoaderRoute: typeof KasirChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/admin/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/couriers': {
      id: '/admin/couriers'
      path: '/admin/couriers'
      fullPath: '/admin/couriers'
      preLoaderRoute: typeof AdminCouriersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCouriersRoute: AdminCouriersRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportsRoute: AdminReportsRoute,
  KasirChatsRoute: KasirChatsRoute,
  KasirComplaintsRoute: KasirComplaintsRoute,
  KasirCouriersRoute: KasirCouriersRoute,
  KasirHandoverRoute: KasirHandoverRoute,
  KasirNewOrderRoute: KasirNewOrderRoute,
  KasirNotifyRoute: KasirNotifyRoute,
  KasirPackagesRoute: KasirPackagesRoute,
  KasirPaymentRoute: KasirPaymentRoute,
  KasirProfileRoute: KasirProfileRoute,
  KasirScanRoute: KasirScanRoute,
  AdminIndexRoute: AdminIndexRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  KasirIndexRoute: KasirIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
